"""Create users and netflix_content tables

Revision ID: f1c55f0463d7
Revises: 
Create Date: 2026-01-20 04:12:48.462600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1c55f0463d7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('netflix_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('show_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('director', sa.Text(), nullable=True),
    sa.Column('cast', sa.Text(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('date_added', sa.String(), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('rating', sa.String(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('listed_in', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_netflix_content_id'), 'netflix_content', ['id'], unique=False)
    op.create_index(op.f('ix_netflix_content_listed_in'), 'netflix_content', ['listed_in'], unique=False)
    op.create_index(op.f('ix_netflix_content_rating'), 'netflix_content', ['rating'], unique=False)
    op.create_index(op.f('ix_netflix_content_release_year'), 'netflix_content', ['release_year'], unique=False)
    op.create_index(op.f('ix_netflix_content_show_id'), 'netflix_content', ['show_id'], unique=True)
    op.create_index(op.f('ix_netflix_content_title'), 'netflix_content', ['title'], unique=False)
    op.create_index(op.f('ix_netflix_content_type'), 'netflix_content', ['type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_netflix_content_type'), table_name='netflix_content')
    op.drop_index(op.f('ix_netflix_content_title'), table_name='netflix_content')
    op.drop_index(op.f('ix_netflix_content_show_id'), table_name='netflix_content')
    op.drop_index(op.f('ix_netflix_content_release_year'), table_name='netflix_content')
    op.drop_index(op.f('ix_netflix_content_rating'), table_name='netflix_content')
    op.drop_index(op.f('ix_netflix_content_listed_in'), table_name='netflix_content')
    op.drop_index(op.f('ix_netflix_content_id'), table_name='netflix_content')
    op.drop_table('netflix_content')
    # ### end Alembic commands ###
